x11()
par(mfrow = c(1, 3), mar = rep(0, 4))
plot(dis$po$Muricoidea$Claremontiella_nodulosa$rf5_wmean)
plot(dis$po$Muricoidea$Claremontiella_nodulosa$maxent5_wmean)
plot(dis$po$Muricoidea$Claremontiella_nodulosa$ens5_wmean)

x11()
par(mfrow = c(1, 3), mar = rep(0, 4))
plot(dis$po$Majoidea$Mithraculus_forceps$rf5_wmean)
plot(dis$po$Majoidea$Mithraculus_forceps$maxent5_wmean)
plot(dis$po$Majoidea$Mithraculus_forceps$ens5_wmean)

x11()
par(mfrow = c(1, 2), mar = rep(0, 4))
plot(dis$po$Muricoidea$Claremontiella_nodulosa$maxent5_wmean)
plot(dis$po$Majoidea$Mithraculus_forceps$maxent5_wmean)

x11()
par(mfrow = c(1, 2), mar = rep(0, 4))
plot(dis$pa$Muricoidea$Claremontiella_nodulosa$ens5_wmean)
plot(dis$pa$Majoidea$Mithraculus_forceps$ens5_wmean)

x11()
par(mfrow = c(1, 2), mar = rep(0, 4))
plot(dis$pa$Majoidea$Stenorhynchus_seticornis$ens5_wmean)
plot(dis$pa$Majoidea$Mithraculus_forceps$ens5_wmean)

x11()
par(mfrow = c(1, 2), mar = rep(0, 4))
plot(dis$po$Muricoidea$Claremontiella_nodulosa$ens5_wmean)
plot(dis$po$Muricoidea$Stramonita_rustica$ens5_wmean)

x11()
par(mfrow = c(1, 3), mar = rep(0, 4))
plot(dis$po$Majoidea$Stenorhynchus_seticornis$rf5_wmean)
plot(dis$po$Majoidea$Stenorhynchus_seticornis$maxent5_wmean)
plot(dis$po$Majoidea$Stenorhynchus_seticornis$ens5_wmean)
